language: android

sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.0
  - android-26
  - extra-android-m2repository
  - extra-android-support

script:
  - "./gradlew assembleRelease"